payfunc/model

source/Error/Error.ts
source/Error/Response.ts
source/Error/client/index.ts
source/Error/client/missingQueryArgument.ts
source/Error/index.ts
source/index.spec.ts
source/index.ts

Depends on #1 to finish first.

Added first attempt at error messages.

---

source/PaymentOption/index.ts
source/index.spec.ts
source/index.ts

The parts you missed when reviewing.

---

Item.spec.ts
Item.ts

A present for you @johnnysolsson.

Item amount

---

Event/Base.ts
Event/Charge.ts
Event/Refund.ts
Event/Type.ts
Event/index.ts
Order.ts
index.ts

What do you think about this @johnnysolsson? Or should we add it to each order item instead?

Added order event.

---

Event/Pay.ts
Event/Type.ts
Event/index.ts
Item.spec.ts
Item.ts
Order.spec..ts
Order.ts
Status.spec.ts
Status.ts
index.ts

Updated with new events
Updated item type
Created new types
Updated old, and created new, unit tests

Initial commit for status updates

---

Payment/index.ts

Simple method. Maybe superfluous. I'm also uncertain about whether to keep it this specific for now or use something like `matchingValue: any` instead of `identifier: Identifier`.

Added filter method to payment

---

Connection.ts

@gabrielonilsson Please take a look at this also.

Hid usage of local storage.

---

Order/Creatable.ts
Order/index.ts

As `meta` can be anything I don't test for it.

Added callback and meta fields to order.

---

Order/Creatable.ts

@gabrielonilsson use this one for the language of PayFunc Send.

Added optional language property to order to select language.

---

Account/Creatable.ts
Account/index.ts
Log/Entry/Creatable.ts
Log/Entry/index.ts
Log/index.ts
Merchant/Creatable.ts
Merchant/index.spec.ts
Merchant/index.ts
Order/Creatable.ts
Order/index.spec.ts
Order/index.ts
User/Base.spec.ts
User/Creatable.spec.ts
User/index.spec.ts
User/index.ts
package-lock.json
package.json

Enabling generation of id:s in client or at first endpoint so that logging can be done using the id of an object from the start.

Enabled early id.

---

Order/index.ts

Should it be tokenised or are a simple base64 encoding/decoding enough?

Callback order url

---

package-lock.json
package.json

authly and cardfunc model bumps

---

Item.ts
Order/index.spec.ts
Order/index.ts
Status.ts

Can someone in particular look at Status.fromEvent and say if the default-case is okay or should be changed?

Amountevent

---

Merchant/Configuration/KeyInfo.ts
Merchant/Configuration/index.ts
Merchant/Key/KeyInfo.spec.ts
Merchant/Key/KeyInfo.ts
Merchant/Key/index.spec.ts
Merchant/Key/index.ts
Merchant/V1/Key/Key.ts
Merchant/index.ts
Order/index.ts
package-lock.json
package.json

Added keyInfo for type checking on unpacked keys in frontend

Merchant keyInfo

---

Merchant/Configuration/Mash.ts
Merchant/Configuration/Sms.ts
Merchant/Creatable.spec.ts
Merchant/Creatable.ts
Merchant/V1/Creatable.spec.ts
Merchant/V1/Creatable.ts
PaymentVerifier/Request.ts
PaymentVerifier/Response/Error.ts
PaymentVerifier/Response/Unverified.ts
PaymentVerifier/Response/VerificationRequired.ts
PaymentVerifier/Response/Verified.ts
PaymentVerifier/Response/index.ts

Fixed merchant-create/update giving terrible feedback from the flaw method of model.Merchant.Creatable.

fixed creatable merchant flaw feedback

---

PaymentVerifier/Response/index.spec.ts
package-lock.json
package.json

Will sync updates to @payfunc/model.Merchant.Key -> @cardfunc/model.Merchant.Configuration -> @cardfunc/Merchant.Emv3d from @cardfunc/model.
Also allow generation of malformed verification errors.

dependency updates

---

Order/index.spec.ts
Order/index.ts
Status.spec.ts
Status.ts

Ensure that the status property always contains the statuses in the same order.

Order status order.

---

Item.ts
Order/amountsPerStatus.spec.ts
Order/index.spec.ts
Order/index.ts
Status.spec.ts
Status.ts

Added function "amounts per status"
Solved issue with refunding a too big value doing total refund after a partial refund.

Added amounts per status

---

Item.ts
Order/index.spec.ts

Bugfix, fail status adds amount on order in portal.

Bugfix, fail status adds amount.

---

Item.ts
Order/index.spec.ts

Bug fix:
Multiple defer events multiplies amount issue fixed.

Bug fix multiple defer events multiplies amount.

---

PaymentVerifier/Response/VerificationRequired.ts

Moved isVerificationError and isCardVerificationError out of class and into namespace to avoid export problems

exported two static functions outside of class

---

Connection.ts

Fixes connection bug related to component and portal having different connections.

Fixes connection bug

---

Event/Settle.spec.ts
Event/Settle.ts
Event/Settlement.ts
Event/Type.ts
Event/index.ts
Status.ts

Weird type related bug required casting in function create. I see nothing wrong so don't know why type system is complaining.

Early prototype

---

Merchant/Key/index.spec.ts
Merchant/Key/index.ts

Changes the API to upgrade a V1 Key.

Fixed url in Key upgrade, API changes

---

Fees.ts
index.ts

Export fees

---

Agent.ts
Key/Actors.ts
Key/Creatable.ts
Key/Key.ts
Key/index.spec.ts
Key/index.ts
package-lock.json
package.json

Added AgentKey type with completely Partial card field

---

Settlement.spec.ts
Settlement.ts

Rebase and keep only "Settlement.toCsv" commit (and potential later commits) before pull request go to review.

Settlement Csv

---

Schedule/index.ts
Schedule/toString.spec.ts
Schedule/toString.ts

Schedule to string

---

Log/Reference.ts
Payment/Card/index.ts
PaymentVerifier/Request.ts
fetch.browser.ts
package-lock.json
package.json
tsconfig.test.json

Cloudflare workers compatability

---

Log/Reference.ts
PaymentVerifier/Request.ts

Update reference to log account number

Update reference with account

---

PaymentVerifier/Response/Verified.ts
PaymentVerifier/Response/index.ts

Pass on verifier token through constructor

Verifier token

---

Key/Actors.ts
Key/Key.ts
Key/V1/index.spec.ts
Merchant.ts
Order/StatusList.ts
Order/index.ts
Status.ts
Subscription/Creatable.ts
package-lock.json
package.json

Circular dependencies.
